version: '3'
services:
  mysql8:
    image: mysql:8.0.27
    container_name: mysql8
    restart: always
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql8/data:/var/lib/mysql
      - ./mysql8/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
    ports:
      - 3306:3306

#     networks:
#       private-network:
#         ipv4_address: 1.1.1.1
# networks:
#   private-network:
#     external:
#       name: private-network
