version: '3'
services:
  postgres14:
    image: postgres:14.0
    container_name: postgres14
    restart: always
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      TZ: "Asia/Bangkok"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    # network_mode: host
    # networks:
    #   private-network:
    #     ipv4_address: 1.1.1.1
    # networks:
    #   private-network:
    #     external:
    #       name: private-network
